### ISSUE TITLE
Is MacOS supported?

### ISSUE THREAD

**Issue by massenz** [tommikaikkonen/prettyprinter#10]
* PrettyPrinter version:
```
$ pip install --no-cache-dir prettyprinter
Collecting prettyprinter
  Downloading prettyprinter-0.8.1-py2.py3-none-any.whl
Requirement already satisfied: colorful>=0.4.0 in ./local/bin/env/dev/lib/python2.7/site-packages (from prettyprinter)
Requirement already satisfied: Pygments>=2.2.0 in ./local/bin/env/dev/lib/python2.7/site-packages (from prettyprinter)
Requirement already satisfied: colorama in ./local/bin/env/dev/lib/python2.7/site-packages (from colorful>=0.4.0->prettyprinter)
Installing collected packages: prettyprinter
Successfully installed prettyprinter-0.8.1
...
```
* Python version:
```
$ python --version
Python 2.7.10
```
* Operating System:
```
$ uname -a
Darwin  17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64
```

### Description
```
$ python
Python 2.7.10 (default, Jul 15 2017, 17:16:57) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from prettyprinter import cpprint
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mmassenzio/local/bin/env/dev/lib/python2.7/site-packages/prettyprinter/__init__.py", line 98
    *,
     ^
SyntaxError: invalid syntax
```
When using a 3.5 virtualenv, instead, this is what happens:
```
$ python
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  5 2015, 21:12:44) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from prettyprinter import cpprint
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mmassenzio/local/bin/env/dev3/lib/python3.5/site-packages/prettyprinter/__init__.py", line 28, in <module>
    import prettyprinter.pretty_stdlib
  File "/Users/mmassenzio/local/bin/env/dev3/lib/python3.5/site-packages/prettyprinter/pretty_stdlib.py", line 252, in <module>
    @register_pretty(Enum)
  File "/Users/mmassenzio/local/bin/env/dev3/lib/python3.5/site-packages/prettyprinter/prettyprinter.py", line 494, in decorator
    assert callable(predicate)
AssertionError
```

### What I Did

I have been happily using `prettyprinter` on my Ubuntu 17.10 box, no issue (Python 3.6).

Unless this is me missing the obvious; or is a known issue with some workaround; I'd be very happy to further investigate and provide PRs: love this tool, would be happy to contribute.

Thanks!

**Comment by tommikaikkonen** [comment]
Thanks for opening the issue! MacOS is indeed supported, and I use that to develop the library. Currently, Python 3.6+ is supported. There is an open issue for supporting Python 3.5 https://github.com/tommikaikkonen/prettyprinter/issues/8, which the latter virtualenv appears to be using. But the way it is failing is weird, as if `enum.Enum` would evaluate to false, causing the `assert callable(predicate)` to be run. I tried running the codebase on 3.5 last night, and I did not get this particular error.

It would be helpful if you can run through the `register_pretty` call in `pdb` to find out what values are causing this, and report back.

**Comment by massenz** [comment]
Thanks for the pointer to use 3.6 (that worked just fine); and I see the issue to support 3.5 is already open, so I'll just close this one.

The error seems to be repeatable (it happened also on another MacOS computer, a Mac Pro): they are both running High Sierra, so maybe there's something related to that? (what version were you running when trying this out?)

Thanks for getting back to me so quickly.

For anyone else stumbling on this via "a well-known search engine" here are the steps:

1. download [Python 3.6 for MacOS](https://www.python.org/ftp/python/3.6.4/python-3.6.4-macosx10.6.pkg) and run the installer;
2. once the installer completes, **open a new terminal**;
3. confirm you have 3.6 as your default `python3`:
```
$ python3 --version
Python 3.6.4
```
4. create a suitable virtualenv & install `prettyprinter`:
```
$ mkvirtualenv -p python3 pp
$ pip install prettyprinter
```
5. verify it's all working "as intended":
```
$ python
Python 3.6.4 (v3.6.4:d48ecebad5, Dec 18 2017, 21:07:28) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from prettyprinter import cpprint
>>> foo = {"a": 33, "beat": 555, "cleat": {"this": "is not a joke"}}
>>> cpprint(foo)
{
    'a': 33,
    'beat': 555,
    'cleat': {'this': 'is not a joke'}
}
```
this should be in gorgeous technicolor.
