### ISSUE TITLE
Hooking the built-in REPL

### ISSUE THREAD

**Issue by njsmith** [tommikaikkonen/prettyprinter#2]
The docs say:

> Unfortunately, it’s not possible to override the representation printer for values evaluated in the default Python shell. I recommend using IPython.

I also recommend using IPython, but is there some reason [`sys.displayhook`](https://docs.python.org/3/library/sys.html#sys.displayhook) won't work?

**Comment by tommikaikkonen** [comment]
I didn't know that existed! In that case, I'll certainly write an integration for it :) Thanks.

**Comment by tommikaikkonen** [comment]
Fixed in https://github.com/tommikaikkonen/prettyprinter/commit/57bc4213e931cf6e24d41950f7cb1ba538a883d1 which is available in the 0.5.0 release that I just uploaded on PyPi 👍
