### ISSUE TITLE
Overriding str pretty-printing (for both pprint and cpprint in Jupyter)

### ISSUE THREAD

**Issue by patarapolw** [tommikaikkonen/prettyprinter#26]
* PrettyPrinter version: 0.14.0
* Python version: 3.7.0
* Operating System: macOS 10.13.6

### Description

I want to insert `hyper_markdownify(s)` into your code, and plan to make text-to-speech (TTS) on click in Jupyter Notebook.

### What I Did

In this repo: https://github.com/patarapolw/pyrepr

```python
import json
from markdownify import markdownify

def hyper_markdownify(s):
    while True:
        try:
            s = json.loads(s)
        except (json.decoder.JSONDecodeError, TypeError):
            break

    return markdownify(s)
```

Most importantly, how do I extract the formatted HTML? I am able to extract the string using 

```python
pprint(obj, StringIO())
```

But I cannot do the same with `cpprint`.

**Comment by tommikaikkonen** [comment]
I'm not a 100% sure what you're asking, but prettyprinter is meant for pretty output of Python data, generally for humans to read—HTML markup and Markdown data that you seem to be working with are data embedded in strings, which prettyprinter does not pretty print other than as generic strings. Feel free to reopen if you provide more context as to what you are trying to achieve.
