### ISSUE TITLE
`requests.structures.CaseInsensitiveDict` does not format correctly

### ISSUE THREAD

**Issue by carlwgeorge** [tommikaikkonen/prettyprinter#32]
* PrettyPrinter version: 0.14.0
* Python version: 3.7.2
* Operating System: Fedora 29

### Description

`requests.structures.CaseInsensitiveDict` does not format correctly with either `pprint` or `cpprint`.

### What I Did

```python
>>> import prettyprinter, requests
>>> r = requests.get('https://httpbin.org')
>>> type(r.headers)
<class 'requests.structures.CaseInsensitiveDict'>
>>> prettyprinter.pprint(r.headers)
{'Connection': 'keep-alive', 'Server': 'gunicorn/19.9.0', 'Date': 'Fri, 15 Feb 2019 16:46:54 GMT', 'Content-Type': 'text/html; charset=utf-8', 'Content-Length': '10122', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Credentials': 'true', 'Via': '1.1 vegur'}
```

One can work around it by wrapping the `CaseInsensitiveDict` with `dict()`, but it would be nice if this wasn't necessary.

```python
>>> prettyprinter.pprint(dict(r.headers))
{
    'Connection': 'keep-alive',
    'Server': 'gunicorn/19.9.0',
    'Date': 'Fri, 15 Feb 2019 16:46:54 GMT',
    'Content-Type': 'text/html; charset=utf-8',
    'Content-Length': '10122',
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Credentials': 'true',
    'Via': '1.1 vegur'
}
```

**Comment by tommikaikkonen** [comment]
The requests pretty printer is not enabled by default. Run this:

```python
prettyprinter.install_extras(['requests'])
```
in the shell and then `prettyprinter.pprint(r.headers)` and you should have the correct output.

I personally have IPython run a script on startup that sets all the prettyprinter extras and settings I need. If you're using the normal shell, there are some instructions here on how to do that: https://prettyprinter.readthedocs.io/en/latest/usage.html#usage-in-the-default-python-shell

One could make a case for the requests extra to be enabled by default, which would definitely be useful. However, I made the decision to leave all extras opt-in. If the extras get out of date and/or break, or they omit some useful information that the library's own `__repr__` method now provides, it's cumbersome to disable pretty printers. And I haven't added any functionality to deregister a pretty printer, which makes it extra cumbersome :)

**Comment by carlwgeorge** [comment]
Ah I didn't realize that.  Based on this line in the README I thought that it should work.

> requests - automatically pretty prints Requests, Responses, Sessions, and more from the requests library

Are the docs out of date, or do they just need to be elaborated on (some requests types work by default, others need an extra step)?

Also, I'm not seeing a clear explanation in the docs of `install_extras` and what it does.  Could that be added?

**Comment by tommikaikkonen** [comment]
I have clarified in the docs that extras need to be enabled - see https://github.com/tommikaikkonen/prettyprinter/commit/57ef4f25c3ef462ec21338b46c17d4c7c9abe747. 

There is an API reference entry for [`install_extras`](https://prettyprinter.readthedocs.io/en/latest/api_reference.html#prettyprinter.install_extras) but it doesn't communicate much more than the function name. I'll expand on that a bit in the next release.

**Comment by carlwgeorge** [comment]
Awesome, thanks!
