### ISSUE TITLE
how to display colors

### ISSUE THREAD

**Issue by Cologler** [tommikaikkonen/prettyprinter#4]
* PrettyPrinter version: 0.4.0 (install from pypi)
* Python version: 3.6.3 x64
* Operating System: windows 10

Seems lose the colors:

![snipaste_2017-12-21_07-41-16](https://user-images.githubusercontent.com/10906962/34233804-58eb9638-e622-11e7-85c4-a2874798199e.png)

![snipaste_2017-12-21_07-41-33](https://user-images.githubusercontent.com/10906962/34233824-748162a6-e622-11e7-9fe5-9ef6ea7e0c2e.png)

**Comment by tommikaikkonen** [comment]
Try `from prettyprinter import cpprint; cpprint('should be colored')` (note the `c` character in front of `pprint`, short for `colored`). That should make it work.

**Comment by Cologler** [comment]
😂 resolved.
