### ISSUE TITLE
Support for types.SimpleNamespace?

### ISSUE THREAD

**Issue by anntzer** [tommikaikkonen/prettyprinter#60]
* PrettyPrinter version: 0.17.0
* Python version: 3.7
* Operating System: linux

### Description

It looks like `types.SimpleNamespace` are not getting prettyprinted.  Given that you already kindly fixed #37 (the C version), I guess supporting the pure Python version should be easy :)

### What I Did

```
In [1]: sys.implementation  # A types.SimpleNamespace
Out[1]: namespace(_multiarch='x86_64-linux-gnu', cache_tag='cpython-37', hexversion=50791408, name='cpython', version=sys.version_info(major=3, minor=7, micro=3, releaselevel='final', serial=0))
```

**Comment by tommikaikkonen** [comment]
Fixed in 0.18.0
