### ISSUE TITLE
Is Python 3.5 supported?

### ISSUE THREAD

**Issue by pquentin** [tommikaikkonen/prettyprinter#8]
I see that you removed f-strings for Read the Docs which runs Python 3.5. Does that mean Python 3.5 is supported? Just asking. Thanks!

**Comment by tommikaikkonen** [comment]
Not fully yet. Python 3.5 doesn't maintain the order of keyword arguments, which `prettyprinter.pretty_call` depends on, so they will appear in undefined order in the output. There are also some standard library changes, e.g. the `fold` property on datetimes which doesn't exist on Python 3.5.

There is some more discussion here https://github.com/ipython/ipython/issues/10953. These issues are quite straightforward to fix and I will gladly accept PRs for them.

**Comment by tommikaikkonen** [comment]
Version `0.11.0` supports Python 3.5. I just uploaded it on PyPi.
